### PR TITLE
added option for custom processor

### PR DESCRIPTION
**Pull request by DMeganoski**
Split TV input properties into groups for simplicity.
Added packageName, className, displayField, and processorAction input properties.
Added options to parameters, input option values and default values can be used if so desired.
Changed output render to reference displayField.
Changed connector.php to check for className and packageName and load custom processor if present.

### CODE REVIEW

**Comment by Jako** [comment]
Thanks for your code, but I solved that custom processor idea a bit different in https://github.com/Jako/SuperBoxSelect/commit/326322721db9cccfcfd5827df1277497502cb748

New types are created quite simple by duplicating a folder inside of 
https://github.com/Jako/SuperBoxSelect/tree/master/core/components/superboxselect/processors/types and modifying the two processors. You could activate the superboxselect system setting 'advanced' and create package based processors with that (experimental and not documented at the moment).

**Comment by DMeganoski** [comment]
Wow. I was expecting you to clean up my newbie code; I know there were a few 'hacks' in there that were not in good modx standards. I was not expecting a complete overhaul. 

I'm not offended at all, I actually made that pull request too quick, there were a few things I thought of changing after I made it. This is actually closer to what I had envisioned.

It seems, though, that you forgot to include the rest of your new javascript files 
https://github.com/Jako/SuperBoxSelect/tree/master/source/js/mgr

In your minified version 
https://github.com/Jako/SuperBoxSelect/blob/master/assets/components/superboxselect/js/mgr/superboxselect.min.js

I was able to get it working with the source files, though. Looks pretty good. I was wondering how you could show/hide fields based on another field's value, that is good to know. I also like your idea of allowing a template instead of just the 'display field'. I am curious how well this will work with html.

If you have not guessed it by now, I'm using this with migx. I would like to use the superbox when representing many to many relationships inside forms.

I am experimenting with the advanced setting now. I'm pretty sure I can get this to work for what I need it to right now. (related users belonging to an extended user class)

The only potential issue that I can foresee is that I am limited to two processors per package. Some functionality may require many tables and many relations, but that is far down the road for me at this point and time, and if that becomes an issue I'll address it then.

Thanks for taking the time to update this. It's much appreciated.

**Comment by Jako** [comment]
HTML is possible in the template. I have added the missing javascripts to the combined and uglified javascript file.

**Comment by Jako** [comment]
And you could have more than one 'type' inside of your custom package.

**Comment by DMeganoski** [comment]
Oh. Well I suppose so since I would have to manually define the 'type' myself in migx. Good to know.

It seems you have also fixed the pagination when used in migx.

One more thing, while we're here. 

When using this with migx, javascript throws an error here
https://github.com/Jako/SuperBoxSelect/blob/master/core/components/superboxselect/elements/tv/input/tpl/superboxselect.render.tpl#L31

because the id is a string when used with migx (and javascript interprets it as a variable). This can simply be fixed by adding quotes around the id.

**Comment by Jako** [comment]
The type could be set with the option `selectType` In the tv options in MIGX.

**Comment by DMeganoski** [comment]
Yes, I've got it working now. I have placed it in a form tab of migx and set the options so that is is populated with my extended user class. Pagination is even working now. Looks great. nice work.

**Comment by DMeganoski** [comment]
Eh, actually I should have debugged a bit more. It turns out that it is still using your user processor.

I have it working now that I have created a new folder under 'processors/types' of your package, but could not get it to work under my own package directory. With enabling the advanced setting and setting a package name, it continues to load the processors from your package directory.

This is functional enough for what I need it to do. But for best practices I'd rather not have to modify your package's folder.

I would envision 'selectPackage' getting passed to your connector and then it uses it to determine where to load the processor from. 

connector.php has not been changed, however, and is still retrieving the processorPath option from your model. It also seems that the 'selectPackage' is not sent to the connector.

Perhaps I am missing something? Is there somewhere else the path to my package is set?

**Comment by Jako** [comment]
I have not tested that feature. Maybe it's not working at the moment.

It should load the superboxselect connector and execute the process of the other package.

**Comment by DMeganoski** [comment]
Okay, that's what I thought. It doesn't seem to be doing that. The processor's path seems to always point to your package.

The path to the processor is being retrieved from the superboxselect model's config array, and although you have included an 'advanced' key in the config array, I don't see any place where it seems the key 'processorPath' is being changed. 

No big hurry, I am going home for the day ^^ And I am sure it is getting late there. Hopefully this info can give you a headstart when you do dig into it.

**Pull request closed without merging**
